/**
 * Public API for state management
 * 
 * This barrel export provides the single source of truth for all state imports.
 * Only export what consumers need - keep internal implementation details private.
 */

// --- Core Atoms ---
export { isMainScriptAtom } from './shared-atoms';
export { openAtom } from './app-lifecycle';
export { promptDataAtom } from './prompt-data';

// --- Shared Atoms ---
export {
  inputAtom,
  _inputAtom,
  submitInputAtom,
  updateInputAtom,
  appendInputAtom,
  setInputAtom,
  blurAtom,
  inputFocusAtom,
  shortcutsAtom,
  submittedAtom,
  loadingAtom,
  runningAtom,
  cancelAtom,
  exitAtom,
  hintAtom,
  actionsAtom,
  actionsFlagsAtom,
  flagsAtom,
  argAtom,
  argsFlagAtom,
  tabIndexAtom,
  tabsAtom,
  tabsHiddenAtom,
  enterButtonDisabledAtom,
  placeholderAtom,
  panelHTMLAtom,
  footerAtom,
  debugAtom,
  logHTMLAtom,
  logLinesAtom,
  selectedAtom,
  preventSubmitAtom,
  scoredChoicesAtom,
  onInputSubmitAtom,
  onEscapeAtom,
  onAbandonAtom,
  onBackAtom,
  onForwardAtom,
  onTabAtom,
  onUpAtom,
  onDownAtom,
  onLeftAtom,
  onRightAtom,
  onPasteAtom,
  onDropAtom,
  onDragEnterAtom,
  onDragLeaveAtom,
  onDragOverAtom,
  onDragStartAtom,
  onDragEndAtom,
  onMenuToggleAtom,
  onFocusedChoiceAtom,
  onChoiceClickAtom,
  onChoiceSubmitAtom,
  submitValueAtom,
  gridAtom,
  directionAtom,
  offsetAtom,
  onMouseEnterAtom,
  onKeyDownAtom,
  onInputChangeAtom,
  processingAtom,
  cacheDbAtom,
  cachedAtom,
  cachedMainAtom,
  cachedPreviewAtom,
  enterAtom,
  metaAtom,
  focusedChoiceAtom,
  previewHTMLAtom,
  descriptionAtom,
  promptBoundsAtom,
  promptDataAtom,
  _promptDataAtom,
  isDropTargetAtom,
  tempThemeAtom,
  defaultChoiceIdAtom,
  defaultValueAtom,
  flaggedChoiceValueAtom,
  prevIndexAtom,
  requiresScrollAtom,
  indexAtom,
  _indexAtom,
  prevScoredChoicesIdsAtom,
  scrollToIndexAtom,
  scrollToItemAtom,
  itemHeightAtom,
  listAtom,
  gridReadyAtom,
  hasActionAtom,
  actionsButtonDisabledAtom,
  choicesConfigAtom,
  mainHeightAtom,
  defaultActionsAtom,
  uiAtom,
  channelAtom,
  pidAtom,
  kitScriptAtom,
  kitAppAtom,
  kitStateAtom,
  kitThemeAtom,
  scriptErrorAtom,
  appearanceAtom,
  toggleAppearanceAtom,
  darkAtom,
  appConfigAtom,
  promptReadyAtom,
  choicesReadyAtom,
  escapeAtom,
  closedDiv,
  noChoice,
  convertAtom,
  termConfigAtom,
  termFontAtom,
  micConfigAtom,
  micMediaRecorderAtom,
  microphoneStateBroadcasterAtom,
  webcamConfigAtom,
  chatConfigAtom,
  chatMessagesAtom,
  chatPushMessageAtom,
  chatHistoryAtom,
  screenConfigAtom,
  kitConfigAtom,
  editorConfigAtom,
  editorViewStateAtom,
  editorCodeLensProviderAtom,
  editorSuggestionsAtom,
  isWindowAtom,
  splashBodyAtom,
  splashProgressAtom,
  splashHeaderAtom,
  splashSetHeaderAtom,
  errorAtom,
  errorMessageAtom,
  resizingAtom,
  resizeEnabledAtom,
  appStateAtom,
  appStateLiteAtom,
  choicesHeightAtom,
  allSkipAtom,
  hasSkipAtom,
  currentChoiceHeightsAtom,
  formDataAtom,
  formHTMLAtom,
  dropZoneAtom,
  dropButtonAtom,
  editorSuggestWidgetVisibleAtom,
  isMouseDownAtom,
  ignoreMouseAtom,
  optionsFocusedAtom,
  optionsAtom,
  optionsConfigAtom,
  actionsInputAtom,
  actionsJustOpenedAtom,
  actionsOpenAtom,
  quickScoreAtom,
  flagsJustOpenedAtom,
  flagsOpenAtom,
  sendActionAtom,
  sendFlagAtom,
  sendKeystrokeAtom,
  choiceInputsAtom,
  micStreamAtom
} from './shared-atoms';

// --- Script State ---
export {
  scriptAtom,
  isKitScriptAtom,
  runningAppScriptAtom,
  scriptErrorAtom as scriptErrorStateAtom
} from './script-state';

// --- App Lifecycle ---
export {
  resetPromptState,
  closeAppAtom
} from './app-lifecycle';

// --- Controllers ---
export { ResizeController } from './controllers/ResizeController';
export { FocusController } from './controllers/FocusController';
export { IPCController } from './controllers/IPCController';

// --- Selectors ---
export * from './selectors/appState';
export * from './selectors/resizeInputs';
export * from './selectors/scriptSelectors';

// --- Types ---
export type { AppState } from './types/app-state';