/**
 * Public API for state management
 *
 * This barrel export provides the single source of truth for all state imports.
 * Only export what consumers need - keep internal implementation details private.
 */

// --- App Lifecycle ---
export {
  closeAppAtom,
  openAtom,
  resetPromptState,
} from './app-lifecycle';
export { FocusController } from './controllers/FocusController';
export { IPCController } from './controllers/IPCController';
// --- Controllers ---
export { ResizeController } from './controllers/ResizeController';
export { promptDataAtom } from './prompt-data';
// --- Script State ---
export {
  isKitScriptAtom,
  runningAppScriptAtom,
  scriptAtom,
  scriptErrorAtom as scriptErrorStateAtom,
} from './script-state';
// --- Selectors ---
export * from './selectors/appState';
export * from './selectors/resizeInputs';
export * from './selectors/scriptSelectors';
// --- Core Atoms ---
// --- Shared Atoms ---
export {
  _indexAtom,
  _inputAtom,
  _promptDataAtom,
  actionsAtom,
  actionsButtonDisabledAtom,
  actionsFlagsAtom,
  actionsInputAtom,
  actionsJustOpenedAtom,
  actionsOpenAtom,
  allSkipAtom,
  appConfigAtom,
  appearanceAtom,
  appendInputAtom,
  appStateAtom,
  appStateLiteAtom,
  argAtom,
  argsFlagAtom,
  blurAtom,
  cacheDbAtom,
  cachedAtom,
  cachedMainAtom,
  cachedPreviewAtom,
  cancelAtom,
  channelAtom,
  chatConfigAtom,
  chatHistoryAtom,
  chatMessagesAtom,
  chatPushMessageAtom,
  choiceInputsAtom,
  choicesConfigAtom,
  choicesHeightAtom,
  choicesReadyAtom,
  closedDiv,
  convertAtom,
  currentChoiceHeightsAtom,
  darkAtom,
  debugAtom,
  defaultActionsAtom,
  defaultChoiceIdAtom,
  defaultValueAtom,
  descriptionAtom,
  directionAtom,
  dropButtonAtom,
  dropZoneAtom,
  editorCodeLensProviderAtom,
  editorConfigAtom,
  editorSuggestionsAtom,
  editorSuggestWidgetVisibleAtom,
  editorViewStateAtom,
  enterAtom,
  enterButtonDisabledAtom,
  errorAtom,
  errorMessageAtom,
  escapeAtom,
  exitAtom,
  flaggedChoiceValueAtom,
  flagsAtom,
  flagsJustOpenedAtom,
  flagsOpenAtom,
  focusedChoiceAtom,
  footerAtom,
  formDataAtom,
  formHTMLAtom,
  gridAtom,
  gridReadyAtom,
  hasActionAtom,
  hasSkipAtom,
  hintAtom,
  ignoreMouseAtom,
  indexAtom,
  inputAtom,
  inputFocusAtom,
  isDropTargetAtom,
  isMainScriptAtom,
  isMouseDownAtom,
  isWindowAtom,
  itemHeightAtom,
  kitAppAtom,
  kitConfigAtom,
  kitScriptAtom,
  kitStateAtom,
  kitThemeAtom,
  listAtom,
  loadingAtom,
  logHTMLAtom,
  logLinesAtom,
  mainHeightAtom,
  metaAtom,
  micConfigAtom,
  micMediaRecorderAtom,
  microphoneStateBroadcasterAtom,
  micStreamAtom,
  noChoice,
  offsetAtom,
  onAbandonAtom,
  onBackAtom,
  onChoiceClickAtom,
  onChoiceSubmitAtom,
  onDownAtom,
  onDragEndAtom,
  onDragEnterAtom,
  onDragLeaveAtom,
  onDragOverAtom,
  onDragStartAtom,
  onDropAtom,
  onEscapeAtom,
  onFocusedChoiceAtom,
  onForwardAtom,
  onInputChangeAtom,
  onInputSubmitAtom,
  onKeyDownAtom,
  onLeftAtom,
  onMenuToggleAtom,
  onMouseEnterAtom,
  onPasteAtom,
  onRightAtom,
  onTabAtom,
  onUpAtom,
  optionsAtom,
  optionsConfigAtom,
  optionsFocusedAtom,
  panelHTMLAtom,
  pidAtom,
  placeholderAtom,
  preventSubmitAtom,
  prevIndexAtom,
  previewHTMLAtom,
  prevScoredChoicesIdsAtom,
  processingAtom,
  promptBoundsAtom,
  promptDataAtom,
  promptReadyAtom,
  quickScoreAtom,
  requiresScrollAtom,
  resizeEnabledAtom,
  resizingAtom,
  runningAtom,
  scoredChoicesAtom,
  screenConfigAtom,
  scriptErrorAtom,
  scrollToIndexAtom,
  scrollToItemAtom,
  selectedAtom,
  sendActionAtom,
  sendFlagAtom,
  sendKeystrokeAtom,
  setInputAtom,
  shortcutsAtom,
  splashBodyAtom,
  splashHeaderAtom,
  splashProgressAtom,
  splashSetHeaderAtom,
  submitInputAtom,
  submittedAtom,
  submitValueAtom,
  tabIndexAtom,
  tabsAtom,
  tabsHiddenAtom,
  tempThemeAtom,
  termConfigAtom,
  termFontAtom,
  toggleAppearanceAtom,
  uiAtom,
  updateInputAtom,
  webcamConfigAtom,
} from './shared-atoms';

// --- Types ---
export type { AppState } from './types/app-state';
