export const SET_PROMPT_TEXT = 'SET_PROMPT_TEXT';
export const SET_TAB_INDEX = 'SET_TAB_INDEX';
export const SHOW_PROMPT_WITH_DATA = 'SHOW_PROMPT_WITH_DATA';
export const UPDATE_PROMPT_CHOICES = 'UPDATE_PROMPT_CHOICES';
export const UPDATE_PROMPT_INFO = 'UPDATE_PROMPT_INFO';
export const VALUE_SUBMITTED = 'VALUE_SUBMITTED';
