export const CLEAR_PROMPT = 'CLEAR_PROMPT';
export const SHOW_PROMPT_WITH_DATA = 'SHOW_PROMPT_WITH_DATA';
export const UPDATE_PROMPT_CHOICES = 'UPDATE_PROMPT_CHOICES';
export const UPDATE_PROMPT_INFO = 'UPDATE_PROMPT_INFO';
