export enum AppChannel {
  PROMPT_HEIGHT_RESET = 'PROMPT_HEIGHT_RESET',
  SET_FILEPATH_BOUNDS = 'SET_PROMPT_DB',
  INIT_RESIZE_HEIGHT = 'INIT_RESIZE_HEIGHT',
  SET_MAIN_HEIGHT = 'SET_MAIN_HEIGHT',
  RESIZE = 'RESIZE',
}
