export enum AppChannel {
  PROMPT_HEIGHT_RESET = 'PROMPT_HEIGHT_RESET',
  SET_FILEPATH_BOUNDS = 'SET_PROMPT_DB',
  INIT_RESIZE_HEIGHT = 'INIT_RESIZE_HEIGHT',
  SET_MAIN_HEIGHT = 'SET_MAIN_HEIGHT',
  RESIZE = 'RESIZE',
  DRAG_FILE_PATH = 'DRAG_FILE_PATH',
  RECEIVE_FILE_CONTENTS = 'RECEIVE_FILE_CONTENTS',
  READ_FILE_CONTENTS = 'READ_FILE_CONTENTS',
  RUN_MAIN_SCRIPT = 'RUN_MAIN_SCRIPT',
  FOCUS_PROMPT = 'FOCUS_PROMPT',
  BUILD_TS_SCRIPT = 'BUILD_TS_SCRIPT',
}
