name: Publish

on:
  push:
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-(${{ matrix.platform }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            platform: win32
            arch: arm64
          - os: script-kit-ubuntu-latest-arm64
            platform: linux
            arch: arm64
          - os: windows-latest
            platform: win32
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: mac
            arch: x64
          - os: macos-latest
            platform: mac
            arch: arm64
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node, pnpm and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Testing ${{ matrix.platform }} ${{ matrix.arch }}
        continue-on-error: true
        run: |
            pnpm i
            pnpm test
